# Generated by Django 5.0.7 on 2024-10-23 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("transcription", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseBrief",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "case_title",
                    models.CharField(blank=True, default=".......", max_length=255),
                ),
                (
                    "case_number",
                    models.CharField(blank=True, default=".......", max_length=100),
                ),
                (
                    "judge_name",
                    models.CharField(blank=True, default=".......", max_length=255),
                ),
                (
                    "accused_name",
                    models.CharField(blank=True, default=".......", max_length=255),
                ),
                (
                    "filtered_transcript",
                    models.TextField(blank=True, default="......."),
                ),
                (
                    "court_type",
                    models.CharField(blank=True, default=".......", max_length=255),
                ),
                (
                    "country",
                    models.CharField(blank=True, default=".......", max_length=100),
                ),
                (
                    "court_location",
                    models.CharField(blank=True, default=".......", max_length=255),
                ),
                (
                    "date",
                    models.CharField(blank=True, default=".......", max_length=100),
                ),
                (
                    "prosecutor_name",
                    models.CharField(blank=True, default=".......", max_length=255),
                ),
                (
                    "defense_counsel_name",
                    models.CharField(blank=True, default=".......", max_length=255),
                ),
                ("charges", models.TextField(blank=True, default=".......")),
                ("plea", models.TextField(blank=True, default=".......")),
                ("verdict", models.TextField(blank=True, default=".......")),
                ("sentence", models.TextField(blank=True, default=".......")),
                ("mitigating_factors", models.TextField(blank=True, default=".......")),
                (
                    "aggravating_factors",
                    models.TextField(blank=True, default="......."),
                ),
                ("legal_principles", models.TextField(blank=True, default=".......")),
                ("precedents_cited", models.TextField(blank=True, default=".......")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transcription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_briefs",
                        to="transcription.transcription",
                    ),
                ),
            ],
        ),
    ]
