# Generated by Django 5.1.2 on 2024-10-30 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transcription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case_matching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.JSONField()),
                ('transcription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcription.transcription')),
            ],
        ),
    ]
