# Generated by Django 5.1.2 on 2024-10-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_matching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_matching',
            name='case',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
