# Generated by Django 5.1.2 on 2024-10-30 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_matching', '0003_alter_case_matching_transcription'),
        ('transcription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_matching',
            name='transcription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Case_matching', to='transcription.transcription'),
        ),
    ]
