# Generated by Django 5.1.2 on 2024-10-31 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_matching', '0005_alter_case_matching_transcription'),
        ('transcription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_matching',
            name='transcription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transcription.transcription'),
        ),
    ]
