# Generated by Django 5.1.2 on 2024-10-31 07:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_matching', '0006_alter_case_matching_transcription'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_matching',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
