# Generated by Django 5.0.7 on 2024-10-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("signups", models.IntegerField(default=0)),
                ("transcribed_cases", models.IntegerField(default=0)),
                ("active_users", models.IntegerField(default=0)),
                ("average_processing_time", models.FloatField(default=0.0)),
            ],
        ),
    ]
